### ISSUE TITLE
[Bug] Running initium-cli from local after ci doesn't seem to update the container on the platform

### ISSUE THREAD

**Issue by LucaLanziani** [nearform/initium-cli#103]
Changing the code and running `initium-cli onbranch` locally after a pipeline did not change the output of the deployed application.

# Steps to reproduce

1. Follow the quick start and deploy the code from branch
2. Add an extra `!` to the `Hello World!` message
3. Run `initium-cli onbranch` from your local copy of the repo
4. curl the endpoind you should have `Hello World!!`

**Comment by zaremba-tomasz** [comment]
Note for myself: image uploaded to the repository contains changes, knative deployment pod is using the old image for some reason.

**Comment by zaremba-tomasz** [comment]
@LucaLanziani the case is reproducible on CI as well:
1. PR creation and initial deployment works as expected.
2. Second commit to the same PR works as expected.
3. Third and subsequent changes are not reflected. SHA of an image is not refreshed by subsequent update calls.

My suggestion to solve this issue is to pass to the manifest not only the `<image-name>:<image-tag>` but extend it to `<image-name>:<image-tag>@<digest>` and be explicit about the image we would like to deploy.

WDYT?

**Comment by LucaLanziani** [comment]
100% that works for me
